# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZTestMMG.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ZTestMMG(object):
    def setupUi(self, ZTestMMG):
        ZTestMMG.setObjectName("ZTestMMG")
        ZTestMMG.resize(665, 238)
        self.centralwidget = QtWidgets.QWidget(ZTestMMG)
        self.centralwidget.setObjectName("centralwidget")
        self.ZstartButton = QtWidgets.QPushButton(self.centralwidget)
        self.ZstartButton.setGeometry(QtCore.QRect(460, 40, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ZstartButton.setFont(font)
        self.ZstartButton.setObjectName("ZstartButton")
        self.ZpropellerSlider = QtWidgets.QSlider(self.centralwidget)
        self.ZpropellerSlider.setGeometry(QtCore.QRect(250, 40, 51, 171))
        self.ZpropellerSlider.setMaximum(150)
        self.ZpropellerSlider.setOrientation(QtCore.Qt.Vertical)
        self.ZpropellerSlider.setObjectName("ZpropellerSlider")
        self.ZpropellerLabel = QtWidgets.QLabel(self.centralwidget)
        self.ZpropellerLabel.setGeometry(QtCore.QRect(230, 20, 221, 21))
        self.ZpropellerLabel.setObjectName("ZpropellerLabel")
        self.ZrudderLabel0 = QtWidgets.QLabel(self.centralwidget)
        self.ZrudderLabel0.setGeometry(QtCore.QRect(40, 20, 151, 20))
        self.ZrudderLabel0.setObjectName("ZrudderLabel0")
        self.ZquitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ZquitButton.setGeometry(QtCore.QRect(510, 150, 75, 23))
        self.ZquitButton.setObjectName("ZquitButton")
        self.ZrudderBox = QtWidgets.QSpinBox(self.centralwidget)
        self.ZrudderBox.setGeometry(QtCore.QRect(50, 70, 51, 22))
        self.ZrudderBox.setMinimum(-45)
        self.ZrudderBox.setMaximum(45)
        self.ZrudderBox.setObjectName("ZrudderBox")
        self.ZrudderLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.ZrudderLabel2.setGeometry(QtCore.QRect(120, 70, 61, 21))
        self.ZrudderLabel2.setObjectName("ZrudderLabel2")
        self.ZpropellerBox = QtWidgets.QSpinBox(self.centralwidget)
        self.ZpropellerBox.setGeometry(QtCore.QRect(330, 110, 61, 22))
        self.ZpropellerBox.setMaximum(150)
        self.ZpropellerBox.setObjectName("ZpropellerBox")
        self.ZpropellerLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.ZpropellerLabel2.setGeometry(QtCore.QRect(410, 110, 61, 21))
        self.ZpropellerLabel2.setObjectName("ZpropellerLabel2")
        #ZTestMMG.setCentralWidget(self.centralwidget)

        self.retranslateUi(ZTestMMG)
        self.ZstartButton.clicked.connect(ZTestMMG.clicked_start)
        self.ZquitButton.released.connect(ZTestMMG.close)
        self.ZpropellerSlider.sliderMoved['int'].connect(ZTestMMG.change_shaft_revolution)
        self.ZrudderBox.valueChanged['int'].connect(ZTestMMG.change_rudder_angle)
        self.ZpropellerSlider.sliderMoved['int'].connect(self.ZpropellerBox.setValue)
        self.ZpropellerBox.valueChanged['int'].connect(self.ZpropellerSlider.setValue)
        self.ZpropellerBox.valueChanged['int'].connect(ZTestMMG.change_shaft_revolution)
        QtCore.QMetaObject.connectSlotsByName(ZTestMMG)

    def retranslateUi(self, ZTestMMG):
        _translate = QtCore.QCoreApplication.translate
        ZTestMMG.setWindowTitle(_translate("ZTestMMG", "MainWindow"))
        self.ZstartButton.setText(_translate("ZTestMMG", "Z TEST START"))
        self.ZpropellerLabel.setText(_translate("ZTestMMG", "Propeller Shaft Revolution [rps]"))
        self.ZrudderLabel0.setText(_translate("ZTestMMG", "Z Test Rudder Angle [deg]"))
        self.ZquitButton.setText(_translate("ZTestMMG", "QUIT"))
        self.ZrudderLabel2.setText(_translate("ZTestMMG", "degree"))
        self.ZpropellerLabel2.setText(_translate("ZTestMMG", "rps"))
